# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-22 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170622_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.Category'),
            preserve_default=False,
        ),
    ]
