# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='/article/static/media/images'),
        ),
    ]
