# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-25 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20170624_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alt',
            field=models.CharField(default='', max_length=245, verbose_name='\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430'),
            preserve_default=False,
        ),
    ]
