# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-03 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_item_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
