# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-03 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_item_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='content',
        ),
    ]
