# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-03 16:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_remove_item_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
