# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_item_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='caption_slider',
            field=models.CharField(default='', max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='text_in_slider',
            field=models.TextField(default='', max_length=255, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0435'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='alt',
            field=models.CharField(max_length=255, verbose_name='\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430'),
        ),
    ]
