# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-06 08:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20170706_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u043e\u0434\u0442\u043e\u0432\u0430\u0440\u0430')),
                ('image', models.ImageField(upload_to='images//%Y/%m/%d')),
                ('alias', models.SlugField(verbose_name='Alias \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('alt', models.CharField(max_length=255, verbose_name='\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430')),
                ('caption_slider', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
                ('text_in_slider', models.TextField(max_length=255, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0435')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0434 \u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u041f\u043e\u0434 \u0422\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Item'),
        ),
    ]
