# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20170706_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, upload_to='images//%Y/%m/%d'),
        ),
    ]
