# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 07:36
from __future__ import unicode_literals

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_item_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('price', models.ImageField(max_length=50, upload_to=b'', verbose_name='\u0426\u0435\u043d\u0430')),
                ('category', models.ForeignKey(on_delete=article.models.Item, to='article.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, upload_to='images//%Y/%m/%d', verbose_name='\u0421\u043a\u0430\u0447\u0430\u0442\u044c \u043a\u0430\u0442\u0430\u043b\u043e\u0433'),
        ),
    ]
