# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20170710_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': '\u0421\u043f\u0435\u0446\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0421\u043f\u0435\u0446\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f'},
        ),
    ]
