# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20170711_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='item',
        ),
        migrations.AddField(
            model_name='special',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='article.Item'),
        ),
        migrations.AlterField(
            model_name='special',
            name='price',
            field=models.IntegerField(max_length=50, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
