# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20170711_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='item',
        ),
        migrations.AddField(
            model_name='special',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Item'),
        ),
    ]
