# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20170711_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='item',
        ),
    ]
