# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_special_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='alias',
            field=models.SlugField(default='', verbose_name='Alias \u0442\u043e\u0432\u0430\u0440\u0430'),
            preserve_default=False,
        ),
    ]
