# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('article', '0026_auto_20170710_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='special',
            name='object_id',
        ),
        migrations.AddField(
            model_name='special',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='special',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Type'),
        ),
    ]
