# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 06:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_special_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
        ),
    ]
