# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '\u041e \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438', 'verbose_name_plural': '\u041e \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'},
        ),
        migrations.AddField(
            model_name='about',
            name='alias',
            field=models.SlugField(default='', verbose_name='Alias \u043e_\u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'),
            preserve_default=False,
        ),
    ]
